version: '3'
services: 
    tests:
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        volumes: 
            - .:/DockerHelloWorld
        command:
            - /bin/bash
            - /DockerHelloWorld/run-tests.sh